/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StayGallery".
 */
export type StayGallery =
  | {
      title?: string | null;
      image: string | Media;
      caption?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'media-categories': MediaCategory;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'form-submission-enquiries': FormSubmissionEnquiry;
    'form-submission-subscribers': FormSubmissionSubscriber;
    'campaign-pages': CampaignPage;
    stays: Stay;
    'newsletter-subscribers': NewsletterSubscriber;
    redirects: Redirect;
    search: Search;
    'campaign-forms': CampaignForm;
    'campaign-leads': CampaignLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-categories': MediaCategoriesSelect<false> | MediaCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'form-submission-enquiries': FormSubmissionEnquiriesSelect<false> | FormSubmissionEnquiriesSelect<true>;
    'form-submission-subscribers': FormSubmissionSubscribersSelect<false> | FormSubmissionSubscribersSelect<true>;
    'campaign-pages': CampaignPagesSelect<false> | CampaignPagesSelect<true>;
    stays: StaysSelect<false> | StaysSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'campaign-forms': CampaignFormsSelect<false> | CampaignFormsSelect<true>;
    'campaign-leads': CampaignLeadsSelect<false> | CampaignLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-header': SiteHeader;
    'site-footer': SiteFooter;
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName: string;
  role: 'admin' | 'editor' | 'author';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  showHeader?: boolean | null;
  showFooter?: boolean | null;
  layout?:
    | (
        | {
            heading?: string | null;
            description?: string | null;
            form: string | CampaignForm;
            backgroundImage?: (string | null) | Media;
            imageOpacity?: number | null;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campaign-form-embed';
          }
        | {
            /**
             * Use this field for full page formatted textual content.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-section';
          }
        | {
            preheading: string;
            heading: string;
            description?: string | null;
            'primary-image'?: (string | null) | Media;
            'secondary-image'?: (string | null) | Media;
            'primary-button'?: {
              label?: string | null;
              link?: string | null;
              openInNewTab?: boolean | null;
            };
            'secondary-button'?: {
              label?: string | null;
              link?: string | null;
              openInNewTab?: boolean | null;
            };
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'multi-image-content';
          }
        | {
            backgroundImage?: (string | null) | Media;
            heading: string;
            description?: string | null;
            redirectLink: 'reference' | 'url';
            url?: string | null;
            pageReference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'enquiry-form';
          }
        | {
            backgroundImage?: (string | null) | Media;
            heading: string;
            description?: string | null;
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'thank-you';
          }
        | HeroSliderBlock
        | SplitContentBlock
        | AppPromoBlock
        | TestimonialsSliderBlock
        | StagesSectionBlock
        | FeatureCardsBlock
        | PricingSectionBlock
        | PageBannerBlock
        | ImageCardsSectionBlock
        | StorySectionBlock
        | FaqSectionBlock
        | ComparisonTableBlock
        | ImageGridSectionBlock
        | CenteredTextSectionBlock
        | FeaturedBlogPostBlock
        | BlogCategoryGridBlock
        | BlogFilterGridBlock
        | {
            layout: 'image-left' | 'image-right';
            preHeading?: string | null;
            mainHeading?: string | null;
            emailAddress?: string | null;
            socialLinks?:
              | {
                  icon: string | Media;
                  handle: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            buttons?:
              | {
                  style?: ('solid' | 'outline' | 'link') | null;
                  solidAnimation?: ('none' | 'circle-fill') | null;
                  outlineAnimation?: ('none' | 'border-trace') | null;
                  label: string;
                  /**
                   * The uploaded icon will automatically inherit the Text Color of the button.
                   */
                  icon?: (string | null) | Media;
                  url: string;
                  newTab?: boolean | null;
                  backgroundColor?: string | null;
                  /**
                   * This color will also apply to the Button Icon.
                   */
                  textColor?: string | null;
                  hoverBackgroundColor?: string | null;
                  hoverTextColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            image: string | Media;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-information';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Paste valid JSON-LD (Schema.org) here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-forms".
 */
export interface CampaignForm {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'campaign-pages';
          value: string | CampaignPage;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-pages".
 */
export interface CampaignPage {
  id: string;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            heading?: string | null;
            description?: string | null;
            form: string | CampaignForm;
            backgroundImage?: (string | null) | Media;
            imageOpacity?: number | null;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campaign-form-embed';
          }
        | {
            /**
             * Use this field for full page formatted textual content.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-section';
          }
        | {
            preheading: string;
            heading: string;
            description?: string | null;
            'primary-image'?: (string | null) | Media;
            'secondary-image'?: (string | null) | Media;
            'primary-button'?: {
              label?: string | null;
              link?: string | null;
              openInNewTab?: boolean | null;
            };
            'secondary-button'?: {
              label?: string | null;
              link?: string | null;
              openInNewTab?: boolean | null;
            };
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'multi-image-content';
          }
        | {
            backgroundImage?: (string | null) | Media;
            heading: string;
            description?: string | null;
            redirectLink: 'reference' | 'url';
            url?: string | null;
            pageReference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'enquiry-form';
          }
        | {
            backgroundImage?: (string | null) | Media;
            heading: string;
            description?: string | null;
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'thank-you';
          }
        | HeroSliderBlock
        | SplitContentBlock
        | AppPromoBlock
        | TestimonialsSliderBlock
        | StagesSectionBlock
        | FeatureCardsBlock
        | PricingSectionBlock
        | PageBannerBlock
        | ImageCardsSectionBlock
        | StorySectionBlock
        | FaqSectionBlock
        | ComparisonTableBlock
        | ImageGridSectionBlock
        | CenteredTextSectionBlock
        | FeaturedBlogPostBlock
        | BlogCategoryGridBlock
        | BlogFilterGridBlock
        | {
            layout: 'image-left' | 'image-right';
            preHeading?: string | null;
            mainHeading?: string | null;
            emailAddress?: string | null;
            socialLinks?:
              | {
                  icon: string | Media;
                  handle: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            buttons?:
              | {
                  style?: ('solid' | 'outline' | 'link') | null;
                  solidAnimation?: ('none' | 'circle-fill') | null;
                  outlineAnimation?: ('none' | 'border-trace') | null;
                  label: string;
                  /**
                   * The uploaded icon will automatically inherit the Text Color of the button.
                   */
                  icon?: (string | null) | Media;
                  url: string;
                  newTab?: boolean | null;
                  backgroundColor?: string | null;
                  /**
                   * This color will also apply to the Button Icon.
                   */
                  textColor?: string | null;
                  hoverBackgroundColor?: string | null;
                  hoverTextColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            image: string | Media;
            paddingTopDesktop?: number | null;
            paddingBottomDesktop?: number | null;
            paddingTopMobile?: number | null;
            paddingBottomMobile?: number | null;
            marginTopDesktop?: number | null;
            marginBottomDesktop?: number | null;
            marginTopMobile?: number | null;
            marginBottomMobile?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-information';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Paste valid JSON-LD (Schema.org) here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  /**
   * Categorize your media to keep your library organized.
   */
  category?: (string | null) | MediaCategory;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories".
 */
export interface MediaCategory {
  id: string;
  title: string;
  /**
   * This is used for filtering and should be lowercase/kebab-case.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock".
 */
export interface HeroSliderBlock {
  heroType: 'video' | 'slider';
  singleVideo?: {
    video: string | Media;
    title?: string | null;
    highlightedTitle: string;
    description?: string | null;
    buttons?:
      | {
          style?: ('solid' | 'outline' | 'link') | null;
          solidAnimation?: ('none' | 'circle-fill') | null;
          outlineAnimation?: ('none' | 'border-trace') | null;
          label: string;
          /**
           * The uploaded icon will automatically inherit the Text Color of the button.
           */
          icon?: (string | null) | Media;
          url: string;
          newTab?: boolean | null;
          backgroundColor?: string | null;
          /**
           * This color will also apply to the Button Icon.
           */
          textColor?: string | null;
          hoverBackgroundColor?: string | null;
          hoverTextColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  slides?:
    | {
        image: string | Media;
        title?: string | null;
        highlightedTitle: string;
        description?: string | null;
        buttons?:
          | {
              style?: ('solid' | 'outline' | 'link') | null;
              solidAnimation?: ('none' | 'circle-fill') | null;
              outlineAnimation?: ('none' | 'border-trace') | null;
              label: string;
              /**
               * The uploaded icon will automatically inherit the Text Color of the button.
               */
              icon?: (string | null) | Media;
              url: string;
              newTab?: boolean | null;
              backgroundColor?: string | null;
              /**
               * This color will also apply to the Button Icon.
               */
              textColor?: string | null;
              hoverBackgroundColor?: string | null;
              hoverTextColor?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero-slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock".
 */
export interface SplitContentBlock {
  layout: 'image-left' | 'image-right';
  image: string | Media;
  preHeading?: string | null;
  mainHeading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description_html?: string | null;
  buttons?:
    | {
        style?: ('solid' | 'outline' | 'link') | null;
        solidAnimation?: ('none' | 'circle-fill') | null;
        outlineAnimation?: ('none' | 'border-trace') | null;
        label: string;
        /**
         * The uploaded icon will automatically inherit the Text Color of the button.
         */
        icon?: (string | null) | Media;
        url: string;
        newTab?: boolean | null;
        backgroundColor?: string | null;
        /**
         * This color will also apply to the Button Icon.
         */
        textColor?: string | null;
        hoverBackgroundColor?: string | null;
        hoverTextColor?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'split-content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppPromoBlock".
 */
export interface AppPromoBlock {
  layout: 'image-left' | 'image-right';
  gradientColor?: string | null;
  image: string | Media;
  preHeading?: string | null;
  mainHeading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description_html?: string | null;
  buttons?:
    | {
        style?: ('solid' | 'outline' | 'link') | null;
        solidAnimation?: ('none' | 'circle-fill') | null;
        outlineAnimation?: ('none' | 'border-trace') | null;
        label: string;
        /**
         * The uploaded icon will automatically inherit the Text Color of the button.
         */
        icon?: (string | null) | Media;
        url: string;
        newTab?: boolean | null;
        backgroundColor?: string | null;
        /**
         * This color will also apply to the Button Icon.
         */
        textColor?: string | null;
        hoverBackgroundColor?: string | null;
        hoverTextColor?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'app-promo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsSliderBlock".
 */
export interface TestimonialsSliderBlock {
  preHeading?: string | null;
  mainHeading: string;
  backgroundImage?: (string | null) | Media;
  /**
   * Set the opacity of the background image from 0 (invisible) to 100 (fully visible).
   */
  bgOpacity?: number | null;
  /**
   * e.g. #CDBEA5 (The gradient will be generated automatically)
   */
  cardBorderColor?: string | null;
  testimonials?:
    | {
        mediaType?: ('none' | 'image' | 'video') | null;
        image?: (string | null) | Media;
        videoUrl?: string | null;
        quote: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials-slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StagesSectionBlock".
 */
export interface StagesSectionBlock {
  /**
   * The full-width image that appears behind the white container.
   */
  backgroundImage: string | Media;
  preHeading?: string | null;
  mainHeading: string;
  subHeading?: string | null;
  stages?:
    | {
        image: string | Media;
        label: string;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  buttons?:
    | {
        style?: ('solid' | 'outline' | 'link') | null;
        solidAnimation?: ('none' | 'circle-fill') | null;
        outlineAnimation?: ('none' | 'border-trace') | null;
        label: string;
        /**
         * The uploaded icon will automatically inherit the Text Color of the button.
         */
        icon?: (string | null) | Media;
        url: string;
        newTab?: boolean | null;
        backgroundColor?: string | null;
        /**
         * This color will also apply to the Button Icon.
         */
        textColor?: string | null;
        hoverBackgroundColor?: string | null;
        hoverTextColor?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stages-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  preHeading?: string | null;
  mainHeading: string;
  subHeading?: string | null;
  /**
   * e.g. #CDBEA5 (The gradient will be generated automatically)
   */
  cardBorderGradient?: string | null;
  cards?:
    | {
        icon: string | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature-cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionBlock".
 */
export interface PricingSectionBlock {
  /**
   * If provided, this image will appear faded behind the pricing section.
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Set the opacity of the background image from 0 (invisible) to 100 (fully visible).
   */
  bgOpacity?: number | null;
  preHeading?: string | null;
  mainHeading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description_html?: string | null;
  plans?:
    | {
        badge?: string | null;
        title: string;
        monthlyOriginalPrice?: string | null;
        monthlyPrice?: string | null;
        yearlyOriginalPrice?: string | null;
        yearlyPrice?: string | null;
        description: string;
        isFeatured?: boolean | null;
        cardBackground?: string | null;
        /**
         * e.g. #CDBEA5 (The gradient will be generated automatically)
         */
        cardBorder?: string | null;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        style?: ('solid' | 'outline' | 'link') | null;
        solidAnimation?: ('none' | 'circle-fill') | null;
        outlineAnimation?: ('none' | 'border-trace') | null;
        label: string;
        /**
         * The uploaded icon will automatically inherit the Text Color of the button.
         */
        icon?: (string | null) | Media;
        url: string;
        newTab?: boolean | null;
        backgroundColor?: string | null;
        /**
         * This color will also apply to the Button Icon.
         */
        textColor?: string | null;
        hoverBackgroundColor?: string | null;
        hoverTextColor?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock".
 */
export interface PageBannerBlock {
  title: string;
  mediaType: 'image' | 'video' | 'slider';
  image?: (string | null) | Media;
  video?: (string | null) | Media;
  slides?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'page-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCardsSectionBlock".
 */
export interface ImageCardsSectionBlock {
  preHeading?: string | null;
  mainHeading: string;
  subHeading?: string | null;
  cards?:
    | {
        image: string | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image-cards-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StorySectionBlock".
 */
export interface StorySectionBlock {
  /**
   * The full-width image that appears behind the white container.
   */
  backgroundImage: string | Media;
  /**
   * Set the opacity of the background image from 0 (invisible) to 100 (fully visible).
   */
  bgOpacity?: number | null;
  preHeading?: string | null;
  mainHeading: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_html?: string | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'story-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock".
 */
export interface FaqSectionBlock {
  /**
   * The background image that appears behind the FAQs (with a light overlay).
   */
  backgroundImage?: (string | null) | Media;
  heading: string;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  heading: string;
  tiers?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        featureName: string;
        tierValues?:
          | {
              hasFeature?: boolean | null;
              textValue?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparison-table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGridSectionBlock".
 */
export interface ImageGridSectionBlock {
  preHeading?: string | null;
  mainHeading: string;
  subHeading?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description_html?: string | null;
  images?:
    | {
        image: string | Media;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image-grid-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CenteredTextSectionBlock".
 */
export interface CenteredTextSectionBlock {
  backgroundColor?: string | null;
  textColor?: string | null;
  /**
   * If provided, this image will appear as a background covering the section.
   */
  backgroundImage?: (string | null) | Media;
  preHeading?: string | null;
  mainHeading?: string | null;
  subHeading?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description_html?: string | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'centered-text-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedBlogPostBlock".
 */
export interface FeaturedBlogPostBlock {
  preHeading?: string | null;
  mainHeading: string;
  post: string | BlogPost;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featured-blog-post';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * This will be used in the URL. It must be unique.
   */
  slug: string;
  category: string | BlogCategory;
  publishedDate: string;
  author?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  card: {
    cardImage: string | Media;
    excerpt: string;
  };
  featuredImage: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Paste valid JSON-LD (Schema.org) here.
     */
    schema?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  title: string;
  /**
   * This is used for filtering and should be lowercase/kebab-case.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogCategoryGridBlock".
 */
export interface BlogCategoryGridBlock {
  preHeading?: string | null;
  mainHeading: string;
  category: string | BlogCategory;
  theme: 'light' | 'dark' | 'beige';
  backgroundImage?: (string | null) | Media;
  imageOpacity?: number | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog-category-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogFilterGridBlock".
 */
export interface BlogFilterGridBlock {
  preHeading?: string | null;
  mainHeading?: string | null;
  theme: 'light' | 'dark' | 'beige';
  backgroundImage?: (string | null) | Media;
  imageOpacity?: number | null;
  paddingTopDesktop?: number | null;
  paddingBottomDesktop?: number | null;
  paddingTopMobile?: number | null;
  paddingBottomMobile?: number | null;
  marginTopDesktop?: number | null;
  marginBottomDesktop?: number | null;
  marginTopMobile?: number | null;
  marginBottomMobile?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog-filter-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-enquiries".
 */
export interface FormSubmissionEnquiry {
  id: string;
  type?: string | null;
  room?: string | null;
  date?: string | null;
  time?: string | null;
  nights?: string | null;
  adults?: string | null;
  children?: string | null;
  comments?: string | null;
  treatment?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phone?: string | null;
  country?: string | null;
  contact?: string | null;
  consent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-subscribers".
 */
export interface FormSubmissionSubscriber {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays".
 */
export interface Stay {
  id: string;
  title: string;
  /**
   * This will be used in the URL. It must be unique.
   */
  slug: string;
  'intro-content'?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: string | Media;
  'stay-gallery'?: StayGallery;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  email: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'campaign-pages';
          value: string | CampaignPage;
        } | null)
      | ({
          relationTo: 'blog-posts';
          value: string | BlogPost;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: string | Page;
      }
    | {
        relationTo: 'blog-posts';
        value: string | BlogPost;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-leads".
 */
export interface CampaignLead {
  id: string;
  page?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'campaign-pages';
        value: string | CampaignPage;
      } | null);
  form: string | CampaignForm;
  name: string;
  email: string;
  submissionData?:
    | {
        fieldName?: string | null;
        fieldValue?: string | null;
        id?: string | null;
      }[]
    | null;
  submissionJSON:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'media-categories';
        value: string | MediaCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'form-submission-enquiries';
        value: string | FormSubmissionEnquiry;
      } | null)
    | ({
        relationTo: 'form-submission-subscribers';
        value: string | FormSubmissionSubscriber;
      } | null)
    | ({
        relationTo: 'campaign-pages';
        value: string | CampaignPage;
      } | null)
    | ({
        relationTo: 'stays';
        value: string | Stay;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'campaign-forms';
        value: string | CampaignForm;
      } | null)
    | ({
        relationTo: 'campaign-leads';
        value: string | CampaignLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showHeader?: T;
  showFooter?: T;
  layout?:
    | T
    | {
        'campaign-form-embed'?:
          | T
          | {
              heading?: T;
              description?: T;
              form?: T;
              backgroundImage?: T;
              imageOpacity?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'content-section'?:
          | T
          | {
              content?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'multi-image-content'?:
          | T
          | {
              preheading?: T;
              heading?: T;
              description?: T;
              'primary-image'?: T;
              'secondary-image'?: T;
              'primary-button'?:
                | T
                | {
                    label?: T;
                    link?: T;
                    openInNewTab?: T;
                  };
              'secondary-button'?:
                | T
                | {
                    label?: T;
                    link?: T;
                    openInNewTab?: T;
                  };
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'enquiry-form'?:
          | T
          | {
              backgroundImage?: T;
              heading?: T;
              description?: T;
              redirectLink?: T;
              url?: T;
              pageReference?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'thank-you'?:
          | T
          | {
              backgroundImage?: T;
              heading?: T;
              description?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
        'hero-slider'?: T | HeroSliderBlockSelect<T>;
        'split-content'?: T | SplitContentBlockSelect<T>;
        'app-promo'?: T | AppPromoBlockSelect<T>;
        'testimonials-slider'?: T | TestimonialsSliderBlockSelect<T>;
        'stages-section'?: T | StagesSectionBlockSelect<T>;
        'feature-cards'?: T | FeatureCardsBlockSelect<T>;
        'pricing-section'?: T | PricingSectionBlockSelect<T>;
        'page-banner'?: T | PageBannerBlockSelect<T>;
        'image-cards-section'?: T | ImageCardsSectionBlockSelect<T>;
        'story-section'?: T | StorySectionBlockSelect<T>;
        'faq-section'?: T | FaqSectionBlockSelect<T>;
        'comparison-table'?: T | ComparisonTableBlockSelect<T>;
        'image-grid-section'?: T | ImageGridSectionBlockSelect<T>;
        'centered-text-section'?: T | CenteredTextSectionBlockSelect<T>;
        'featured-blog-post'?: T | FeaturedBlogPostBlockSelect<T>;
        'blog-category-grid'?: T | BlogCategoryGridBlockSelect<T>;
        'blog-filter-grid'?: T | BlogFilterGridBlockSelect<T>;
        'contact-information'?:
          | T
          | {
              layout?: T;
              preHeading?: T;
              mainHeading?: T;
              emailAddress?: T;
              socialLinks?:
                | T
                | {
                    icon?: T;
                    handle?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    style?: T;
                    solidAnimation?: T;
                    outlineAnimation?: T;
                    label?: T;
                    icon?: T;
                    url?: T;
                    newTab?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    hoverBackgroundColor?: T;
                    hoverTextColor?: T;
                    id?: T;
                  };
              image?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock_select".
 */
export interface HeroSliderBlockSelect<T extends boolean = true> {
  heroType?: T;
  singleVideo?:
    | T
    | {
        video?: T;
        title?: T;
        highlightedTitle?: T;
        description?: T;
        buttons?:
          | T
          | {
              style?: T;
              solidAnimation?: T;
              outlineAnimation?: T;
              label?: T;
              icon?: T;
              url?: T;
              newTab?: T;
              backgroundColor?: T;
              textColor?: T;
              hoverBackgroundColor?: T;
              hoverTextColor?: T;
              id?: T;
            };
      };
  slides?:
    | T
    | {
        image?: T;
        title?: T;
        highlightedTitle?: T;
        description?: T;
        buttons?:
          | T
          | {
              style?: T;
              solidAnimation?: T;
              outlineAnimation?: T;
              label?: T;
              icon?: T;
              url?: T;
              newTab?: T;
              backgroundColor?: T;
              textColor?: T;
              hoverBackgroundColor?: T;
              hoverTextColor?: T;
              id?: T;
            };
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock_select".
 */
export interface SplitContentBlockSelect<T extends boolean = true> {
  layout?: T;
  image?: T;
  preHeading?: T;
  mainHeading?: T;
  description?: T;
  description_html?: T;
  buttons?:
    | T
    | {
        style?: T;
        solidAnimation?: T;
        outlineAnimation?: T;
        label?: T;
        icon?: T;
        url?: T;
        newTab?: T;
        backgroundColor?: T;
        textColor?: T;
        hoverBackgroundColor?: T;
        hoverTextColor?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppPromoBlock_select".
 */
export interface AppPromoBlockSelect<T extends boolean = true> {
  layout?: T;
  gradientColor?: T;
  image?: T;
  preHeading?: T;
  mainHeading?: T;
  description?: T;
  description_html?: T;
  buttons?:
    | T
    | {
        style?: T;
        solidAnimation?: T;
        outlineAnimation?: T;
        label?: T;
        icon?: T;
        url?: T;
        newTab?: T;
        backgroundColor?: T;
        textColor?: T;
        hoverBackgroundColor?: T;
        hoverTextColor?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsSliderBlock_select".
 */
export interface TestimonialsSliderBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  backgroundImage?: T;
  bgOpacity?: T;
  cardBorderColor?: T;
  testimonials?:
    | T
    | {
        mediaType?: T;
        image?: T;
        videoUrl?: T;
        quote?: T;
        name?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StagesSectionBlock_select".
 */
export interface StagesSectionBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  preHeading?: T;
  mainHeading?: T;
  subHeading?: T;
  stages?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  bottomText?: T;
  buttons?:
    | T
    | {
        style?: T;
        solidAnimation?: T;
        outlineAnimation?: T;
        label?: T;
        icon?: T;
        url?: T;
        newTab?: T;
        backgroundColor?: T;
        textColor?: T;
        hoverBackgroundColor?: T;
        hoverTextColor?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock_select".
 */
export interface FeatureCardsBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  subHeading?: T;
  cardBorderGradient?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionBlock_select".
 */
export interface PricingSectionBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  bgOpacity?: T;
  preHeading?: T;
  mainHeading?: T;
  description?: T;
  description_html?: T;
  plans?:
    | T
    | {
        badge?: T;
        title?: T;
        monthlyOriginalPrice?: T;
        monthlyPrice?: T;
        yearlyOriginalPrice?: T;
        yearlyPrice?: T;
        description?: T;
        isFeatured?: T;
        cardBackground?: T;
        cardBorder?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        style?: T;
        solidAnimation?: T;
        outlineAnimation?: T;
        label?: T;
        icon?: T;
        url?: T;
        newTab?: T;
        backgroundColor?: T;
        textColor?: T;
        hoverBackgroundColor?: T;
        hoverTextColor?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock_select".
 */
export interface PageBannerBlockSelect<T extends boolean = true> {
  title?: T;
  mediaType?: T;
  image?: T;
  video?: T;
  slides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCardsSectionBlock_select".
 */
export interface ImageCardsSectionBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  subHeading?: T;
  cards?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StorySectionBlock_select".
 */
export interface StorySectionBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  bgOpacity?: T;
  preHeading?: T;
  mainHeading?: T;
  content?: T;
  content_html?: T;
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock_select".
 */
export interface FaqSectionBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  heading?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  heading?: T;
  tiers?:
    | T
    | {
        name?: T;
        id?: T;
      };
  features?:
    | T
    | {
        featureName?: T;
        tierValues?:
          | T
          | {
              hasFeature?: T;
              textValue?: T;
              id?: T;
            };
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGridSectionBlock_select".
 */
export interface ImageGridSectionBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  subHeading?: T;
  description?: T;
  description_html?: T;
  images?:
    | T
    | {
        image?: T;
        title?: T;
        id?: T;
      };
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CenteredTextSectionBlock_select".
 */
export interface CenteredTextSectionBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  textColor?: T;
  backgroundImage?: T;
  preHeading?: T;
  mainHeading?: T;
  subHeading?: T;
  description?: T;
  description_html?: T;
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedBlogPostBlock_select".
 */
export interface FeaturedBlogPostBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  post?: T;
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogCategoryGridBlock_select".
 */
export interface BlogCategoryGridBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  category?: T;
  theme?: T;
  backgroundImage?: T;
  imageOpacity?: T;
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogFilterGridBlock_select".
 */
export interface BlogFilterGridBlockSelect<T extends boolean = true> {
  preHeading?: T;
  mainHeading?: T;
  theme?: T;
  backgroundImage?: T;
  imageOpacity?: T;
  paddingTopDesktop?: T;
  paddingBottomDesktop?: T;
  paddingTopMobile?: T;
  paddingBottomMobile?: T;
  marginTopDesktop?: T;
  marginBottomDesktop?: T;
  marginTopMobile?: T;
  marginBottomMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories_select".
 */
export interface MediaCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  card?:
    | T
    | {
        cardImage?: T;
        excerpt?: T;
      };
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-enquiries_select".
 */
export interface FormSubmissionEnquiriesSelect<T extends boolean = true> {
  type?: T;
  room?: T;
  date?: T;
  time?: T;
  nights?: T;
  adults?: T;
  children?: T;
  comments?: T;
  treatment?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  country?: T;
  contact?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-subscribers_select".
 */
export interface FormSubmissionSubscribersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-pages_select".
 */
export interface CampaignPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        'campaign-form-embed'?:
          | T
          | {
              heading?: T;
              description?: T;
              form?: T;
              backgroundImage?: T;
              imageOpacity?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'content-section'?:
          | T
          | {
              content?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'multi-image-content'?:
          | T
          | {
              preheading?: T;
              heading?: T;
              description?: T;
              'primary-image'?: T;
              'secondary-image'?: T;
              'primary-button'?:
                | T
                | {
                    label?: T;
                    link?: T;
                    openInNewTab?: T;
                  };
              'secondary-button'?:
                | T
                | {
                    label?: T;
                    link?: T;
                    openInNewTab?: T;
                  };
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'enquiry-form'?:
          | T
          | {
              backgroundImage?: T;
              heading?: T;
              description?: T;
              redirectLink?: T;
              url?: T;
              pageReference?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
        'thank-you'?:
          | T
          | {
              backgroundImage?: T;
              heading?: T;
              description?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
        'hero-slider'?: T | HeroSliderBlockSelect<T>;
        'split-content'?: T | SplitContentBlockSelect<T>;
        'app-promo'?: T | AppPromoBlockSelect<T>;
        'testimonials-slider'?: T | TestimonialsSliderBlockSelect<T>;
        'stages-section'?: T | StagesSectionBlockSelect<T>;
        'feature-cards'?: T | FeatureCardsBlockSelect<T>;
        'pricing-section'?: T | PricingSectionBlockSelect<T>;
        'page-banner'?: T | PageBannerBlockSelect<T>;
        'image-cards-section'?: T | ImageCardsSectionBlockSelect<T>;
        'story-section'?: T | StorySectionBlockSelect<T>;
        'faq-section'?: T | FaqSectionBlockSelect<T>;
        'comparison-table'?: T | ComparisonTableBlockSelect<T>;
        'image-grid-section'?: T | ImageGridSectionBlockSelect<T>;
        'centered-text-section'?: T | CenteredTextSectionBlockSelect<T>;
        'featured-blog-post'?: T | FeaturedBlogPostBlockSelect<T>;
        'blog-category-grid'?: T | BlogCategoryGridBlockSelect<T>;
        'blog-filter-grid'?: T | BlogFilterGridBlockSelect<T>;
        'contact-information'?:
          | T
          | {
              layout?: T;
              preHeading?: T;
              mainHeading?: T;
              emailAddress?: T;
              socialLinks?:
                | T
                | {
                    icon?: T;
                    handle?: T;
                    url?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    style?: T;
                    solidAnimation?: T;
                    outlineAnimation?: T;
                    label?: T;
                    icon?: T;
                    url?: T;
                    newTab?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    hoverBackgroundColor?: T;
                    hoverTextColor?: T;
                    id?: T;
                  };
              image?: T;
              paddingTopDesktop?: T;
              paddingBottomDesktop?: T;
              paddingTopMobile?: T;
              paddingBottomMobile?: T;
              marginTopDesktop?: T;
              marginBottomDesktop?: T;
              marginTopMobile?: T;
              marginBottomMobile?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        schema?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays_select".
 */
export interface StaysSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  'intro-content'?: T;
  featuredImage?: T;
  'stay-gallery'?: T | StayGallerySelect<T>;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StayGallery_select".
 */
export interface StayGallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-forms_select".
 */
export interface CampaignFormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-leads_select".
 */
export interface CampaignLeadsSelect<T extends boolean = true> {
  page?: T;
  form?: T;
  name?: T;
  email?: T;
  submissionData?:
    | T
    | {
        fieldName?: T;
        fieldValue?: T;
        id?: T;
      };
  submissionJSON?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: string;
  logo: string | Media;
  logoAlt?: (string | null) | Media;
  noticeText?: string | null;
  primaryCTA: {
    label: string;
    url: string;
    newTab?: boolean | null;
  };
  navigationLinks?:
    | {
        linkType: 'url' | 'reference';
        label: string;
        url?: string | null;
        pageReference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        newTab?: boolean | null;
        dropdownLinks?:
          | {
              linkType: 'url' | 'reference';
              label: string;
              url?: string | null;
              pageReference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  menuLinksPrimary?:
    | {
        linkType: 'url' | 'reference';
        label: string;
        url?: string | null;
        pageReference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        newTab?: boolean | null;
        dropdownLinks?:
          | {
              linkType: 'url' | 'reference';
              label: string;
              url?: string | null;
              pageReference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  menuLinksSecondary?:
    | {
        linkType: 'url' | 'reference';
        label: string;
        url?: string | null;
        pageReference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        newTab?: boolean | null;
        dropdownLinks?:
          | {
              linkType: 'url' | 'reference';
              label: string;
              url?: string | null;
              pageReference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: string;
  followUsHeading?: string | null;
  instagramHandle?: string | null;
  feedImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  newsletterHeading?: string | null;
  newsletterDescription?: string | null;
  emailPlaceholder?: string | null;
  newsletterCTA?: string | null;
  logo: string | Media;
  legalLinks?:
    | {
        linkType: 'url' | 'reference';
        label: string;
        url?: string | null;
        pageReference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        newTab?: boolean | null;
        dropdownLinks?:
          | {
              linkType: 'url' | 'reference';
              label: string;
              url?: string | null;
              pageReference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  socialLinks?:
    | {
        platform: 'instagram' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: string;
  siteName: string;
  siteLink: string;
  favicon?: (string | null) | Media;
  logo?: (string | null) | Media;
  icon?: (string | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    x?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    whatsapp?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (string | null) | Media;
    /**
     * Paste valid JSON-LD (Schema.org) here.
     */
    metaSchema?: string | null;
  };
  error404?: {
    heading?: string | null;
    message?: string | null;
    backgroundImage?: (string | null) | Media;
    ctaLabel?: string | null;
  };
  error500?: {
    heading?: string | null;
    message?: string | null;
    backgroundImage?: (string | null) | Media;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  logo?: T;
  logoAlt?: T;
  noticeText?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
      };
  navigationLinks?:
    | T
    | {
        linkType?: T;
        label?: T;
        url?: T;
        pageReference?: T;
        newTab?: T;
        dropdownLinks?:
          | T
          | {
              linkType?: T;
              label?: T;
              url?: T;
              pageReference?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  menuLinksPrimary?:
    | T
    | {
        linkType?: T;
        label?: T;
        url?: T;
        pageReference?: T;
        newTab?: T;
        dropdownLinks?:
          | T
          | {
              linkType?: T;
              label?: T;
              url?: T;
              pageReference?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  menuLinksSecondary?:
    | T
    | {
        linkType?: T;
        label?: T;
        url?: T;
        pageReference?: T;
        newTab?: T;
        dropdownLinks?:
          | T
          | {
              linkType?: T;
              label?: T;
              url?: T;
              pageReference?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  followUsHeading?: T;
  instagramHandle?: T;
  feedImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterDescription?: T;
  emailPlaceholder?: T;
  newsletterCTA?: T;
  logo?: T;
  legalLinks?:
    | T
    | {
        linkType?: T;
        label?: T;
        url?: T;
        pageReference?: T;
        newTab?: T;
        dropdownLinks?:
          | T
          | {
              linkType?: T;
              label?: T;
              url?: T;
              pageReference?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  siteName?: T;
  siteLink?: T;
  favicon?: T;
  logo?: T;
  icon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        x?: T;
        youtube?: T;
        tiktok?: T;
        whatsapp?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        metaSchema?: T;
      };
  error404?:
    | T
    | {
        heading?: T;
        message?: T;
        backgroundImage?: T;
        ctaLabel?: T;
      };
  error500?:
    | T
    | {
        heading?: T;
        message?: T;
        backgroundImage?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}